version: '3.1'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
  chat:
   image: ninotbs/pvs-chat:latest
   restart: always
   ports:
      - 3000:3000
   depends_on:
      - redis
   environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
    